# 数据库连接地址
spring.datasource.url=jdbc:mysql://localhost:3306/book_db?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true

# 数据库用户名
spring.datasource.username=root

# 数据库密码（改成你自己的）
spring.datasource.password=123456

# 自动建表：update 表示程序启动时自动更新表结构
spring.jpa.hibernate.ddl-auto=update

# 在控制台打印 SQL 语句（方便学习）
spring.jpa.show-sql=true

#日志配置
logging.level.com.example2.demo2=INFO
logging.file.name=logs/book-manager.log

knife4j.enable=true
